version: "3"

services:
  express:
    image: node:lts
    tty: true
    expose:
      - 9229
      - 3001
    ports:
      - 9229:9229
      - 3001:3000
    volumes:
      - ./:/src
    working_dir: "/src/backend"
    command: npm run start:debug

  mysql:
    build: ./db/dockerfile
    platform: linux/x86_64
    expose:
      - 3306
    volumes:
      - ./db/my.cnf:/etc/db/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: week7_db
    ports:
      - 3306:3306

  next:
    image: node:lts
    tty: true
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./:/src
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    working_dir: "/src/frontend"